// Generated by CoffeeScript 1.6.3
(function() {
  var initialized;

  initialized = false;

  exports.call_count = 0;

  exports.$init = function($coffeeCb, next) {
    var cb;
    if (!initialized) {
      cb = $coffeeCb;
      this.register('black').from.factory(function($moreData) {
        return cb($moreData);
      });
      initialized = true;
    }
    return exports.call_count++;
  };

}).call(this);
